### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by clintonb** [gocd-contrib/gomatic#17]
Recent discussion on https://github.com/SpringerSBM/gomatic/pull/10 has lead to my, and others, wondering the state of this project. Is this project still maintained? If so, who are the maintainers?

If this package is not maintained, can the following steps be taken?

1. Now: Update the README to reflect the state of the project, and request new maintainers.
2. Later: Transfer ownership of the project (including the PyPI package) to new maintainers.
3. Later: Update the README of this repo to point to the location of the new repo.

**Comment by clintonb** [comment]
FYI @Drakekin @gbigwood @savagematt

**Comment by moritzheiber** [comment]
Love to get this clarified and to kickstart development again. This is literally the only viable project to keep complex GoCD configurations in code.

**Comment by macdiesel** [comment]
@hilverd I spoke with our team here and we are willing to take over ownership of this project. I would be the admin and we have a few others who could help. I think edX has a lot we can contribute to this project and use it extensively. 

This project has been a great help to us and we would like to see it continue to move forward. Thank you for all of your work.

**Comment by MFAnderson** [comment]
@hilverd there's a few people here at ThoughtWorks, myself included, who would also be quite keen to provide support. @macdiesel, @clintonb, would y'all be interested in some sort of communal ownership under the https://github.com/gocd-contrib org?

**Comment by macdiesel** [comment]
@MFAnderson I think we would be fine with that. Our cycles on gomatic and our gomatic scripts can be sporadic now the the bulk of our lift to migrate to GoCD is complete. Our main concern is the ability to get some fixes patched in to gomatic as quickly as possible. Obviously releasing software is not our main business, though getting features to production greatly benefits us.

What we would really like would be a way to quickly get the patches in to gomatic that we need to continue our operations. An example of the types of things we have added have been fixes for ssl support, exposing unencrypted secure variables to jobs and stages, shallow cloning and integration tests to ensure upstream artifacts exist. 

As long as we have a pathway for quickly landing these improvements and thoughtworks is open to pulling in these changes I do not believe we would have objections to you and your team owning the project. It is much more in your wheelhouse than ours. =)

**Comment by MFAnderson** [comment]
@macdiesel sorry, I guess I didn't convey myself well. I was hoping that we would work collaboratively on it. The gocd-contrib org is largely for discoverability purposes and edX's fork looks great, so was hoping to maybe move it under that org but have you (and potentially other folks from edX) included as owners on the repo.

**Comment by macdiesel** [comment]
@MFAnderson That sounds fine and we are willing to do this.

Let me know what I can do to get the ball rolling.

**Comment by moritzheiber** [comment]
Transferring ownership of the repository towards gocd-contrib would be the next logical step I presume?

**Comment by hilverd-springer** [comment]
Hi @moritzheiber, if you could please give me permission to create repositories on gocd-contrib, then I can transfer the repository.

**Comment by MFAnderson** [comment]
Hey @hilverd-springer, trying to get permissions sorted out with the owners of the org. I have 'create repo' but not 'invite to org'.

**Comment by hilverd-springer** [comment]
Thanks @MFAnderson. I've done the transfer (feel free to have me removed from `gocd-contrib`), please let me know what to do with the PyPI package.

**Comment by MFAnderson** [comment]
@hilverd-springer not sure what the right long term home is for it, but you can transfer it to me for the time being PyPI username is the same as github.

**Comment by hilverd-springer** [comment]
@MFAnderson Done.

**Comment by hanej** [comment]
I am so happy development is continuing with the project.  Thank you for picking it up!

**Comment by macdiesel** [comment]
🎉
