### ISSUE TITLE
Update PyPI credentials and create a new release

### ISSUE THREAD

**Issue by clintonb** [gocd-contrib/gomatic#26]
The PyPI credentials in .travis.yml still use the previous maintainer's credentials. Update these to use a current maintainer's credentials. setup.py will also need to be updated.

Additionally, create a new release and publish to PyPI.

**Comment by clintonb** [comment]
@MFAnderson do you now have PyPI access? Can you add the user edx as a collaborator there?

**Comment by MFAnderson** [comment]
@clintonb added

**Comment by dudadornelles** [comment]
I've tagged the current master with 0.4.15 and in theory we should get a new release once travis is done. After that we can keep on following the instructions on how to release from the README.

**Comment by MFAnderson** [comment]
Initial version got messed up, have redone as 0.5.0 to reflect substantial changes including preliminary python3 support in new version. Now up on PyPI @ https://pypi.python.org/pypi/gomatic/0.5.0
