### ISSUE TITLE
How far back should we consider backwards compatibility?

### ISSUE THREAD

**Issue by MFAnderson** [gocd-contrib/gomatic#31]
The integration tests at present test for all versions from 13.1 onwards. This currently means 30 distinct releases are being tested spanning 4 and a half years. This contributes to a very long integration test cycle that results in it not being run very often. Opening this issue to start discussion about if we want to limit the set of old versions we want to support.

**Comment by hanej** [comment]
I'd say continual support for at least the last two major releases

**Comment by clintonb** [comment]
Anyone know the deprecation strategy for GoCD itself? If one exists, I say follow it and support the current versions. Otherwise, I agree with supporting a fixed number of versions.

**Comment by hanej** [comment]
I'm not sure if they have a deprecation strategy.  We had support for a bit and were a few versions behind and it never came up as a problem.  I don't see anything on their site.

**Comment by dudadornelles** [comment]
@arvindsv hey want to pitch in?

**Comment by dudadornelles** [comment]
On a side not, at https://developer.gocd.org/ the oldest version you can download is 16.3.0 so I'd go with that.

**Comment by MFAnderson** [comment]
The older versions are still hosted, just not visibly linked (the integration tests pull them all from the gocd.org server), but limiting support to the ones shown on the site sounds good to me.

**Comment by arvindsv** [comment]
@dudadornelles Sorry. My notifications for this repo were somehow turned off. Now they are on, and I'll pitch in when I can. Thanks.
