### ISSUE TITLE
Modify artifacts definition to include the type attribute

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd-contrib/gomatic#52]
There has been a schema migration to use the same xml element to represent different types of artifacts. Here's the PR that introduced the change - https://github.com/gocd/gocd/pull/4278

```
<artifact src="foo" dest="bar" />
<test src="baz" />
``` 

gets converted to

```
<artifact type="build" src="foo" dest="bar" />
<artifact type="test" src="baz" />
```

**Comment by dudadornelles** [comment]
Thanks for the heads up!

**Comment by dudadornelles** [comment]
It would seem this https://github.com/gocd-contrib/gomatic/pull/53 does the trick for this issue?

**Comment by arvindsv** [comment]
👍

**Comment by dudadornelles** [comment]
Awesome thanks to all involved :)
